import {
  ArrowLeft as ArrowLeftIcon,
  Award as AwardIcon,
  Bell as BellIcon,
  Brain as BrainIcon,
  CalendarDays as CalendarDaysIcon,
  Check as CheckIcon,
  CheckCircle as CheckCircleIcon,
  ChevronRight as ChevronRightIcon,
  ClipboardList as ClipboardListIcon,
  Clock3 as Clock3Icon,
  Download as DownloadIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Filter as FilterIcon,
  GraduationCap as GraduationCapIcon,
  HeartHandshake as HeartHandshakeIcon,
  HeartPulse as HeartPulseIcon,
  Image as ImageIcon,
  KeyRound as KeyRoundIcon,
  LayoutDashboard as LayoutDashboardIcon,
  Library as LibraryIcon,
  Lock as LockIcon,
  Mail as MailIcon,
  MapPin as MapPinIcon,
  Menu as MenuIcon,
  Minus as MinusIcon,
  Monitor as MonitorIcon,
  MoonStar as MoonStarIcon,
  MoreVertical as MoreVerticalIcon,
  Phone as PhoneIcon,
  Plus as PlusIcon,
  School as SchoolIcon,
  Search as SearchIcon,
  ShieldAlert as ShieldAlertIcon,
  ShieldCheck as ShieldCheckIcon,
  SlidersHorizontal as SlidersHorizontalIcon,
  Smartphone as SmartphoneIcon,
  Smile as SmileIcon,
  Sparkles as SparklesIcon,
  SquarePen as SquarePenIcon,
  Star as StarIcon,
  SunMedium as SunMediumIcon,
  Trash2 as Trash2Icon,
  Upload as UploadIcon,
  User as UserIcon,
  Users as UsersIcon,
  X as XIcon,
  XCircle as XCircleIcon,
} from "lucide-react";
import {
  IconFileText,
  IconAddressBook,
  IconBooks,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandTwitter,
  IconBriefcase,
  IconBuildingHospital,
  IconBuildingStore,
  IconCalendarEvent,
  IconCalendarTime,
  IconCamera,
  IconCategory,
  IconChartBar,
  IconChevronDown,
  IconClipboardHeart,
  IconCloud,
  IconCreditCard,
  IconHelpCircle,
  IconHome,
  IconLicense,
  IconLogout,
  IconMessageCircle,
  IconMessageHeart,
  IconNotes,
  IconPackage,
  IconSchool,
  IconSettings,
  IconShoppingBag,
  IconShoppingCart,
  IconSortAscending2,
  IconSortDescending2,
  IconStethoscope,
  IconUserCircle,
  IconUserHeart,
  IconUsers,
  IconUsersGroup,
  IconVideo,
  IconClipboardList,
  IconPhoto,
  IconClockHour4,
  IconMapPin,
  IconNotification,
  IconBrandTiktok,
  IconHomeHeart,
  IconStar,
  IconPill,
  IconHeartbeat,
  IconBolt,
  IconActivityHeartbeat,
  IconShieldHeart,
} from "@tabler/icons-react";
import { iconNames, type AppIconName } from "@workspace/shared/constants";

export const reactAppIconMap: Record<AppIconName, any> = {
  ArrowLeftIcon,
  AwardIcon,
  BellIcon,
  BrainIcon,
  CalendarDaysIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronRightIcon,
  ClipboardListIcon,
  Clock3Icon,
  DownloadIcon,
  EyeIcon,
  EyeOffIcon,
  FilterIcon,
  GraduationCapIcon,
  HeartHandshakeIcon,
  HeartPulseIcon,
  ImageIcon,
  KeyRoundIcon,
  LayoutDashboardIcon,
  LibraryIcon,
  LockIcon,
  MailIcon,
  MapPinIcon,
  MenuIcon,
  MinusIcon,
  MonitorIcon,
  MoonStarIcon,
  MoreVerticalIcon,
  PhoneIcon,
  PlusIcon,
  SchoolIcon,
  SearchIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SlidersHorizontalIcon,
  SmartphoneIcon,
  SmileIcon,
  SparklesIcon,
  SquarePenIcon,
  StarIcon,
  SunMediumIcon,
  Trash2Icon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  XCircleIcon,
  XIcon,
  IconAddressBook,
  IconBooks,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandTwitter,
  IconBriefcase,
  IconBuildingHospital,
  IconBuildingStore,
  IconCalendarEvent,
  IconCalendarTime,
  IconCamera,
  IconCategory,
  IconChartBar,
  IconChevronDown,
  IconClipboardHeart,
  IconCloud,
  IconCreditCard,
  IconHelpCircle,
  IconHome,
  IconLicense,
  IconLogout,
  IconMessageCircle,
  IconMessageHeart,
  IconNotes,
  IconPackage,
  IconSchool,
  IconSettings,
  IconShoppingBag,
  IconShoppingCart,
  IconSortAscending2,
  IconSortDescending2,
  IconStethoscope,
  IconUserCircle,
  IconUserHeart,
  IconUsers,
  IconUsersGroup,
  IconVideo,
  IconClipboardList,
  IconPhoto,
  IconClockHour4,
  IconMapPin,
  IconNotification,
  IconBrandTiktok,
  IconHomeHeart,
  IconStar,
  IconFileText,
  IconPill,
  IconHeartbeat,
  IconBolt,
  IconActivityHeartbeat,
  IconShieldHeart,
};

export const appIconMap = reactAppIconMap;
export { iconNames };
export type { AppIconName };
