import { Text, View } from "react-native";

import { Badge } from "@/components/ui/badge";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty";
import { GradientCard } from "@/components/shared/gradient-card";
import { InternalScreen } from "@/components/internal/internal-screen";
import { SectionCard } from "@/components/shared/section-card";
import { Skeleton } from "@/components/ui/skeleton";
import { useProgressReports } from "@/hooks/use-healthcare";
import { formatDate } from "@workspace/shared/utils";

function ProgressReportsSkeleton() {
  return (
    <InternalScreen>
      <View className="section-wrapper gap-4 pt-6">
        <Skeleton className="h-10 w-48 rounded-full" />
        <Skeleton className="h-64 w-full rounded-[28px]" />
      </View>
    </InternalScreen>
  );
}

export default function AdminProgressReportsRoute() {
  const { data, isLoading } = useProgressReports({ limit: 100 });

  if (isLoading) return <ProgressReportsSkeleton />;

  const reports = data?.progressReports ?? [];

  return (
    <InternalScreen>
      <View className="section-wrapper gap-6 pb-8 pt-6">
        <View className="gap-2">
          <Text className="font-primary text-3xl text-foreground">
            Progress Reports
          </Text>
          <Text className="font-secondary text-sm leading-7 text-muted-foreground">
            All generated psychiatric progress reports across patients.
          </Text>
        </View>

        <SectionCard
          title="All Reports"
          className="shadow-soft"
          contentClassName="gap-3"
        >
          {reports.length ? (
            reports.map((report) => (
              <GradientCard key={report.id} variant="info">
                <View className="gap-1">
                  <View className="flex-row flex-wrap items-center gap-2">
                    <Text className="font-secondary text-sm font-semibold text-foreground flex-shrink">
                      {report.title}
                    </Text>
                    <Badge
                      variant={report.status === "published" ? "success" : "muted"}
                      className="capitalize text-xs"
                    >
                      {report.status}
                    </Badge>
                  </View>
                  <Text className="font-secondary text-xs text-muted-foreground">
                    {formatDate(report.periodStart, { mode: "date" })}
                    {" - "}
                    {formatDate(report.periodEnd, { mode: "date" })}
                  </Text>
                  {report.patient?.user && (
                    <Text className="font-secondary text-xs text-muted-foreground">
                      Patient: {report.patient.user.displayName}
                    </Text>
                  )}
                  {report.generatedBy && (
                    <Text className="font-secondary text-xs text-muted-foreground">
                      Generated by {report.generatedBy.displayName}
                    </Text>
                  )}
                </View>
              </GradientCard>
            ))
          ) : (
            <Empty>
              <EmptyMedia>
                <EmptyHeader />
              </EmptyMedia>
              <EmptyTitle>No reports yet</EmptyTitle>
              <EmptyDescription>
                Progress reports will appear here after they are generated from the dashboard.
              </EmptyDescription>
            </Empty>
          )}
        </SectionCard>
      </View>
    </InternalScreen>
  );
}
