import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    auth: "src/auth/index.ts",
    "auth/dto": "src/auth/dto.ts",
    user: "src/user/index.ts",
    "user/dto": "src/user/dto.ts",
    admin: "src/admin/index.ts",
    "admin/dto": "src/admin/dto.ts",
    business: "src/business/index.ts",
    "business/dto": "src/business/dto.ts",
    "job-listing": "src/job-listing/index.ts",
    "job-listing/dto": "src/job-listing/dto.ts",
    testimonial: "src/testimonial/index.ts",
    "testimonial/dto": "src/testimonial/dto.ts",
    patient: "src/patient/index.ts",
    "patient/dto": "src/patient/dto.ts",
    post: "src/post/index.ts",
    "post/dto": "src/post/dto.ts",
    category: "src/category/index.ts",
    "category/dto": "src/category/dto.ts",
    provider: "src/provider/index.ts",
    "provider/dto": "src/provider/dto.ts",
    availability: "src/availability/index.ts",
    "availability/dto": "src/availability/dto.ts",
    appointment: "src/appointment/index.ts",
    "appointment/dto": "src/appointment/dto.ts",
    chat: "src/chat/index.ts",
    "chat/dto": "src/chat/dto.ts",
    payment: "src/payment/index.ts",
    "payment/dto": "src/payment/dto.ts",
    campaign: "src/campaign/index.ts",
    "campaign/dto": "src/campaign/dto.ts",
    audit: "src/audit/index.ts",
    "audit/dto": "src/audit/dto.ts",
    traffic: "src/traffic/index.ts",
    "traffic/dto": "src/traffic/dto.ts",
    contact: "src/contact/index.ts",
    "contact/dto": "src/contact/dto.ts",
    newsletter: "src/newsletter/index.ts",
    "newsletter/dto": "src/newsletter/dto.ts",
    dashboard: "src/dashboard/index.ts",
    media: "src/media/index.ts",
    "media/dto": "src/media/dto.ts",
    notification: "src/notification/index.ts",
    "notification/dto": "src/notification/dto.ts",
    staff: "src/staff/index.ts",
    "staff/dto": "src/staff/dto.ts",
    "treatment-plan": "src/treatment-plan/index.ts",
    "treatment-plan/dto": "src/treatment-plan/dto.ts",
    "behavior-program": "src/behavior-program/index.ts",
    "behavior-program/dto": "src/behavior-program/dto.ts",
    "session-note": "src/session-note/index.ts",
    "session-note/dto": "src/session-note/dto.ts",
    "data-point": "src/data-point/index.ts",
    "data-point/dto": "src/data-point/dto.ts",
    "staff-assignment": "src/staff-assignment/index.ts",
    "staff-assignment/dto": "src/staff-assignment/dto.ts",
    "insurance-authorization": "src/insurance-authorization/index.ts",
    "insurance-authorization/dto": "src/insurance-authorization/dto.ts",
    "caregiver-access": "src/caregiver-access/index.ts",
    "caregiver-access/dto": "src/caregiver-access/dto.ts",
    "staff-permission": "src/staff-permission/index.ts",
    "staff-permission/dto": "src/staff-permission/dto.ts",
    "clinical-form": "src/clinical-form/index.ts",
    "clinical-form/dto": "src/clinical-form/dto.ts",
    "progress-report": "src/progress-report/index.ts",
    "progress-report/dto": "src/progress-report/dto.ts",
    onboarding: "src/onboarding/index.ts",
    "onboarding/dto": "src/onboarding/dto.ts",
    "lib/schema": "src/lib/schema.ts",
  },
  outDir: "dist",
  format: ["esm"],
  target: "es2024",
  sourcemap: true,
  clean: true,
  dts: true,
  minify: false,
  deps: {
    neverBundle: [
      "@workspace/shared",
      "@workspace/db",
      "zod",
      "nestjs-zod",
      "react",
      "@types/react",
      "@tabler/icons-react",
    ],
  },
});
