"use client";

import React from "react";
import Link from "next/link";
import { Plus, FileBarChart2, Download, Trash2, Eye } from "lucide-react";
import { toast } from "sonner";
import { formatDate } from "@workspace/shared/utils";
import { Button } from "@workspace/ui/components/button";
import { Badge } from "@workspace/ui/components/badge";
import { Skeleton } from "@workspace/ui/components/skeleton";
import SectionCard from "@workspace/ui/shared/SectionCard";
import PageIntro from "@workspace/ui/shared/PageIntro";
import {
  useProgressReports,
  useDeleteProgressReport,
  useDownloadProgressReportPdf,
} from "@/hooks/progress-report";
import { InfoNotice } from "@workspace/ui/shared/InfoNotice";

const statusVariant = (status: string): "default" | "secondary" => {
  return status === "published" ? "default" : "secondary";
};

const PatientProgressReportsPage = ({
  params,
}: PageProps<"/patients/[id]/progress-reports">) => {
  const { id } = React.use(params);
  const { data, isLoading, fetchError } = useProgressReports({ patientId: id, limit: 50 });
  const { deleteAsync, isDeleting } = useDeleteProgressReport();
  const { downloadAsync, isDownloading } = useDownloadProgressReportPdf();

  const handleDelete = async (reportId: string, title: string) => {
    if (!confirm(`Delete report "${title}"?`)) return;
    try {
      await deleteAsync(reportId);
      toast.success("Report deleted.");
    } catch (err: any) {
      toast.error("Failed to delete.", { description: err?.message });
    }
  };

  const handleDownload = async (reportId: string) => {
    try {
      await downloadAsync(reportId);
    } catch (err: any) {
      toast.error("PDF download failed.", { description: err?.message });
    }
  };

  const reports = data?.progressReports ?? [];

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <PageIntro
          title="Progress Reports"
          description="Generate and manage psychiatric progress reports for this patient. Published reports are visible to the patient."
        />
        <Button asChild className="shrink-0">
          <Link href={`/patients/${id}/progress-reports/new`}>
            <Plus className="size-4 mr-1" />
            Generate Report
          </Link>
        </Button>
      </div>

      {fetchError ? (
        <InfoNotice
          variant="error"
          message={
            fetchError.message ??
            "Could not load these records. Please refresh and try again."
          }
        />
      ) : isLoading ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-24 w-full rounded-lg" />
          ))}
        </div>
      ) : reports.length === 0 ? (
        <SectionCard title="No Reports">
          <div className="flex min-h-40 flex-col items-center justify-center gap-2 rounded-xl border border-dashed text-center">
            <FileBarChart2 className="size-8 text-muted-foreground/50" />
            <p className="text-sm font-medium">No progress reports yet</p>
            <p className="text-xs text-muted-foreground">
              Generate a report to summarize session data, programs, and mastery
              progress for a reporting period.
            </p>
          </div>
        </SectionCard>
      ) : (
        <div className="space-y-3">
          {reports.map((report) => (
            <SectionCard key={report.id} contentClassName="space-y-3">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                <div className="space-y-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="font-medium text-sm">{report.title}</p>
                    <Badge
                      variant={statusVariant(report.status)}
                      className="capitalize text-xs"
                    >
                      {report.status}
                    </Badge>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    {formatDate(report.periodStart, { mode: "date" })} -{" "}
                    {formatDate(report.periodEnd, { mode: "date" })}
                  </p>
                  {report.generatedBy && (
                    <p className="text-xs text-muted-foreground">
                      Generated by {report.generatedBy.displayName} ·{" "}
                      {formatDate(report.createdAt, { mode: "datetime" })}
                    </p>
                  )}
                </div>

                <div className="flex shrink-0 flex-wrap gap-2">
                  <Button asChild variant="outline" size="sm">
                    <Link href={`/patients/${id}/progress-reports/${report.id}`}>
                      <Eye className="size-3.5 mr-1" />
                      View
                    </Link>
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleDownload(report.id)}
                    disabled={isDownloading}
                  >
                    <Download className="size-3.5 mr-1" />
                    PDF
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    className="text-destructive hover:text-destructive"
                    onClick={() => handleDelete(report.id, report.title)}
                    disabled={isDeleting}
                  >
                    <Trash2 className="size-3.5" />
                  </Button>
                </div>
              </div>
            </SectionCard>
          ))}
        </div>
      )}
    </div>
  );
};

export default PatientProgressReportsPage;
