"use client";

import React from "react";
import Link from "next/link";
import { ArrowLeft, Download, FileBarChart2 } from "lucide-react";
import { toast } from "sonner";
import { formatDate } from "@workspace/shared/utils";
import { Button } from "@workspace/ui/components/button";
import { Badge } from "@workspace/ui/components/badge";
import { Skeleton } from "@workspace/ui/components/skeleton";
import SectionCard from "@workspace/ui/shared/SectionCard";
import PageIntro from "@workspace/ui/shared/PageIntro";
import {
  useProgressReport,
  useUpdateProgressReport,
  useDownloadProgressReportPdf,
} from "@/hooks/progress-report";
import { normalizeProgressReportContent } from "@workspace/contracts/progress-report";
import type { ProgressReportContent } from "@workspace/contracts/progress-report";

const statLabel = (label: string, value: string | number) => (
  <div className="flex flex-col gap-0.5">
    <span className="text-xs text-muted-foreground">{label}</span>
    <span className="text-sm font-medium">{value}</span>
  </div>
);

const masteryBadge = (status: ProgressReportContent["behaviorPrograms"][0]["masteryStatus"]) => {
  const map = {
    mastered: { label: "Mastered", variant: "default" as const },
    inProgress: { label: "In Progress", variant: "secondary" as const },
    notStarted: { label: "Not Started", variant: "outline" as const },
  };
  const { label, variant } = map[status] ?? map.notStarted;
  return <Badge variant={variant} className="text-xs">{label}</Badge>;
};

const ProgressReportDetailPage = ({
  params,
}: PageProps<"/patients/[id]/progress-reports/[reportId]">) => {
  const { id: patientId, reportId } = React.use(params);
  const { data: report, isLoading } = useProgressReport(reportId);
  const { updateAsync, isUpdating } = useUpdateProgressReport(reportId);
  const { downloadAsync, isDownloading } = useDownloadProgressReportPdf();

  const handleToggleStatus = async () => {
    if (!report) return;
    const nextStatus = report.status === "published" ? "draft" : "published";
    try {
      await updateAsync({ status: nextStatus });
      toast.success(`Report ${nextStatus === "published" ? "published" : "moved to draft"}.`);
    } catch (err: any) {
      toast.error("Failed to update status.", { description: err?.message });
    }
  };

  const handleDownload = async () => {
    try {
      await downloadAsync(reportId);
    } catch (err: any) {
      toast.error("PDF download failed.", { description: err?.message });
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-64" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-48 w-full" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex flex-col items-center justify-center min-h-40 gap-2 text-center">
        <FileBarChart2 className="size-8 text-muted-foreground/50" />
        <p className="text-sm font-medium">Report not found</p>
        <Button asChild variant="outline" size="sm">
          <Link href={`/patients/${patientId}/progress-reports`}>
            <ArrowLeft className="size-3.5 mr-1" />
            Back to Reports
          </Link>
        </Button>
      </div>
    );
  }

  // Older reports carry an earlier content shape, so normalise before reading.
  const content = normalizeProgressReportContent(report.content);

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div className="space-y-1">
          <Button asChild variant="ghost" size="sm" className="-ml-2 mb-1 text-muted-foreground">
            <Link href={`/patients/${patientId}/progress-reports`}>
              <ArrowLeft className="size-3.5 mr-1" />
              Progress Reports
            </Link>
          </Button>
          <PageIntro
            title={report.title}
            description={`${formatDate(report.periodStart, { mode: "date" })} - ${formatDate(report.periodEnd, { mode: "date" })}`}
          />
          <div className="flex flex-wrap items-center gap-2 pt-1">
            <Badge
              variant={report.status === "published" ? "default" : "secondary"}
              className="capitalize"
            >
              {report.status}
            </Badge>
            {report.generatedBy && (
              <span className="text-xs text-muted-foreground">
                Generated by {report.generatedBy.displayName} ·{" "}
                {formatDate(report.createdAt, { mode: "datetime" })}
              </span>
            )}
          </div>
        </div>

        <div className="flex shrink-0 flex-wrap gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleToggleStatus}
            disabled={isUpdating}
          >
            {report.status === "published" ? "Unpublish" : "Publish"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownload}
            disabled={isDownloading}
          >
            <Download className="size-3.5 mr-1" />
            Download PDF
          </Button>
        </div>
      </div>

      {/* Patient & Provider Summary */}
      <SectionCard title="Report Summary">
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          {statLabel("Patient", content.patient.name)}
          {content.patient.dob && statLabel("Date of Birth", content.patient.dob)}
          {content.provider && statLabel("Provider", content.provider.name)}
          {content.treatmentPlan && statLabel("Treatment Plan", content.treatmentPlan.title)}
        </div>
      </SectionCard>

      {/* Session Statistics */}
      <SectionCard title="Session Statistics">
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">
          {statLabel("Total Sessions", content.sessionStats.total)}
          {statLabel("Total Minutes", content.sessionStats.totalMinutes)}
          {statLabel(
            "Avg Duration",
            `${Math.round(content.sessionStats.averageDurationMinutes)} min`,
          )}
          {content.sessionStats.firstSession &&
            statLabel(
              "First Session",
              formatDate(content.sessionStats.firstSession, { mode: "date" }),
            )}
          {content.sessionStats.lastSession &&
            statLabel(
              "Last Session",
              formatDate(content.sessionStats.lastSession, { mode: "date" }),
            )}
        </div>
      </SectionCard>

      {/* Data Points */}
      {content.dataPointSummary.totalTrials > 0 && (
        <SectionCard title="Data Points">
          <div className="grid grid-cols-2 gap-4">
            {statLabel("Total Trials", content.dataPointSummary.totalTrials)}
            {statLabel("Programs With Data", content.dataPointSummary.programsWithData)}
          </div>
        </SectionCard>
      )}

      {/* Care Programs */}
      {content.behaviorPrograms.length > 0 ? (
        <SectionCard title="Care Programs">
          <div className="space-y-3">
            {content.behaviorPrograms.map((prog, i) => (
              <div
                key={i}
                className="flex flex-col gap-2 rounded-lg border bg-muted/30 p-3 sm:flex-row sm:items-center sm:justify-between"
              >
                <div className="space-y-0.5">
                  <p className="text-sm font-medium">{prog.name}</p>
                  <p className="text-xs text-muted-foreground capitalize">
                    {prog.type.replace(/([A-Z])/g, " $1").trim()} ·{" "}
                    {prog.sessionsCount} session{prog.sessionsCount !== 1 ? "s" : ""}
                    {prog.lastSessionDate &&
                      ` · Last: ${formatDate(prog.lastSessionDate, { mode: "date" })}`}
                  </p>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  <span className="text-sm font-semibold">
                    {prog.masteryPercent}%
                  </span>
                  {masteryBadge(prog.masteryStatus)}
                </div>
              </div>
            ))}
          </div>
        </SectionCard>
      ) : (
        <SectionCard title="Care Programs">
          <p className="text-sm text-muted-foreground">
            No care programs had session data in this period.
          </p>
        </SectionCard>
      )}
    </div>
  );
};

export default ProgressReportDetailPage;
