"use client";

import { FileBarChart2, UserRound } from "lucide-react";
import type {
  ProgressReportQueryType,
  ProgressReportResponse,
} from "@workspace/contracts/progress-report";
import { formatDate } from "@workspace/shared/utils";
import { Badge } from "@workspace/ui/components/badge";
import type { ColumnConfig } from "@workspace/ui/shared/GenericTable";
import ListPage from "@workspace/ui/shared/ListPage";

import { useProgressReports } from "@/hooks/progress-report";

const STATUS_VARIANT: Record<string, "default" | "secondary"> = {
  published: "default",
  draft: "secondary",
};

const columns: ColumnConfig<ProgressReportResponse, ProgressReportQueryType>[] = [
  {
    header: "Title",
    accessor: (report) => (
      <div className="min-w-0 max-w-[20rem] space-y-1">
        <p className="truncate font-semibold">{report.title}</p>
        <p className="truncate text-xs text-muted-foreground">
          {formatDate(report.periodStart, { mode: "date" })} -{" "}
          {formatDate(report.periodEnd, { mode: "date" })}
        </p>
      </div>
    ),
    className: "w-[22rem]",
    wrapperCn: "max-w-[22rem]",
  },
  {
    header: "Patient",
    accessor: (report) => (
      <div className="min-w-0 max-w-[16rem] space-y-1">
        <p className="truncate font-medium">{report.patient?.user.displayName}</p>
        <p className="truncate text-sm text-muted-foreground">
          {report.patient?.user.email ?? "No email"}
        </p>
      </div>
    ),
    className: "w-[17rem]",
    wrapperCn: "max-w-[17rem]",
  },
  {
    header: "Status",
    accessor: (report) => (
      <Badge variant={STATUS_VARIANT[report.status] ?? "secondary"} className="capitalize">
        {report.status}
      </Badge>
    ),
  },
  {
    header: "Generated By",
    accessor: (report) => (
      <span className="text-sm">{report.generatedBy?.displayName ?? "Unknown"}</span>
    ),
  },
  {
    header: "Generated",
    accessor: (report) => formatDate(report.createdAt, { mode: "datetime" }),
    sortKey: "createdAt",
  },
];

const getMoreActions = (report: ProgressReportResponse) => [
  {
    label: "Open patient",
    href: `/patients/${report.patientId}`,
    icon: <UserRound className="size-4" />,
    hidden: !report.patientId,
  },
  {
    label: "View report",
    href: `/patients/${report.patientId}/progress-reports/${report.id}`,
    icon: <FileBarChart2 className="size-4" />,
    hidden: !report.patientId,
  },
];

const ProgressReportsClinicalPage = () => {
  return (
    <ListPage
      dataKey="progressReports"
      entityType="Progress Reports"
      columns={columns}
      useDefaultActions={false}
      canAdd={false}
      moreActions={getMoreActions}
      defaultSortBy="createdAt"
      defaultSearchBy="title"
      searchByOptions={[{ label: "Title", value: "title" }]}
      useListHook={useProgressReports}
      filterConfig={[
        {
          key: "status",
          label: "Status",
          options: [
            { label: "Draft", value: "draft" },
            { label: "Published", value: "published" },
          ],
        },
      ]}
    />
  );
};

export default ProgressReportsClinicalPage;
