import type { ContentBlock } from "../content-blocks";

export const traumaPtsdTreatmentBlocks: ContentBlock[] = [
  {
    type: "callout",
    heading: "You will not be asked to tell the story before you are ready",
    body:
      "A common reason people avoid seeking help for trauma is the expectation that they will have to describe what happened, in detail, to a stranger. That is not how a first psychiatric visit works here. Your provider needs to understand how symptoms are affecting you now, which does not require a full account of the event. You control what you share and when. If retelling would be destabilising today, say so, and the visit will work around it.",
    variant: "info",
    tone: "plain",
  },
  {
    type: "prose",
    eyebrow: "What is happening",
    heading: "Trauma is not a memory problem, it is a threat-response problem",
    paragraphs: [
      "Ordinary memories get filed. They acquire a time stamp and move into the past, so recalling them feels like remembering. Traumatic memories are frequently stored differently, without that filing, which is why they can return as fragments that feel like they are happening now rather than being recalled from then.",
      "That explains most of what people find confusing about their own symptoms. Why a smell can produce a full-body reaction before any conscious thought. Why the response is so disproportionate to the trigger. Why intellectually knowing you are safe changes nothing about what your body does. None of this is a failure of reasoning, because the reaction is not being generated by the reasoning part of the brain.",
      "It also explains why hypervigilance persists long after danger has passed. A threat-detection system that has been through something genuinely dangerous recalibrates to catch it earlier next time. That recalibration is protective in the environment that produced it and exhausting everywhere else.",
      "Trauma is not confined to a single catastrophic event either. Prolonged exposure to harm, particularly in childhood or within a relationship, produces symptoms that look different and are sometimes misread as a personality difficulty rather than the injury they are.",
    ],
  },
  {
    type: "grid",
    eyebrow: "How it presents",
    heading: "The forms PTSD symptoms take",
    intro:
      "Not everyone has all of these, and many people have symptoms they have never connected to trauma at all.",
    items: [
      {
        title: "Intrusive memories and flashbacks",
        description:
          "Unwanted recollections arriving without warning, ranging from a vivid image to a full sensory experience of being back in the event. Distinct from ordinary remembering in that they feel present rather than past.",
      },
      {
        title: "Nightmares and disrupted sleep",
        description:
          "Repetitive dreams of the event or of themes from it, often with waking in fear. Sleep loss then amplifies every other symptom, which is why sleep is frequently the first treatment target.",
      },
      {
        title: "Avoidance",
        description:
          "Steering around places, people, conversations, and reminders. It works briefly and narrows life steadily, which is how a world contracts over years without any single decision to shrink it.",
      },
      {
        title: "Hypervigilance and startle",
        description:
          "Scanning for danger constantly, sitting facing the door, jumping at sounds. Physically draining, and frequently the symptom that partners notice first.",
      },
      {
        title: "Numbing and detachment",
        description:
          "Feeling flat, distant from people, or watching yourself from outside. Often mistaken for not caring, when it is the nervous system reducing volume on everything to keep the unbearable parts manageable.",
      },
      {
        title: "Negative shifts in belief",
        description:
          "Persistent conclusions about yourself or the world: that you are permanently damaged, that nobody can be trusted, that it was your fault. These are symptoms of the injury rather than accurate assessments.",
      },
      {
        title: "Irritability and anger",
        description:
          "A short fuse that arrives faster than thought. Common, frequently shaming, and frequently the reason relationships strain before anyone identifies trauma as the cause.",
      },
      {
        title: "Physical symptoms",
        description:
          "Chronic pain, gastrointestinal problems, headaches, and unexplained fatigue occur at higher rates after trauma. A body held in threat response for years generates real physical consequences.",
      },
      {
        title: "Substance use",
        description:
          "Alcohol and other substances are extremely common ways of managing intrusion and sleep. Approached as an understandable response rather than a separate moral failing, and treated alongside rather than as a precondition.",
      },
    ],
  },
  {
    type: "comparison",
    eyebrow: "Setting expectations",
    heading: "What medication can and cannot do here",
    intro:
      "Being straightforward about this matters. Medication has a real but specific role in trauma treatment, and overstating it sets people up for disappointment.",
    columns: ["", "Medication", "Trauma-focused therapy"],
    rows: [
      [
        "Main effect",
        "Lowers symptom intensity: sleep, hyperarousal, mood, anxiety",
        "Changes how the memory itself is stored and carried",
      ],
      [
        "Effect on nightmares",
        "Some agents specifically target trauma-related nightmares",
        "Nightmares often reduce as processing progresses",
      ],
      [
        "Durability",
        "Benefit is generally present while treatment continues",
        "Gains typically persist after treatment ends",
      ],
      [
        "Evidence position",
        "Supported, and considered second-line to therapy for core PTSD",
        "First-line in every major treatment guideline",
      ],
      [
        "Best role",
        "Lowering symptoms enough that therapy becomes possible",
        "The treatment that addresses the underlying injury",
      ],
      [
        "What it will not do",
        "Erase memories or resolve the trauma itself",
        "Work well when sleep and arousal are entirely unmanaged",
      ],
    ],
    footnote:
      "This is why the usual plan combines both. Medication frequently creates the stability that makes trauma-focused therapy tolerable.",
  },
  {
    type: "process",
    eyebrow: "How care runs",
    heading: "A trauma-informed first visit and what follows",
    steps: [
      {
        title: "You set the pace",
        description:
          "Before anything else, your provider establishes that you decide what to discuss and when, and that you can pause or stop at any point. This is not a formality. Control is the thing trauma removes, and restoring it is part of the treatment.",
      },
      {
        title: "Symptoms first, history second",
        description:
          "The immediate clinical need is to understand what is happening now: sleep, intrusion, avoidance, arousal, mood, and safety. A detailed account of events is not required to build a treatment plan.",
      },
      {
        title: "Screening for what travels alongside",
        description:
          "Depression, panic, substance use, and chronic pain co-occur with PTSD at high rates. Missing them produces a plan that treats a third of the problem.",
        note: "Traumatic brain injury and sleep apnea are also screened for, since both can mimic or amplify PTSD symptoms.",
      },
      {
        title: "Stabilise sleep and arousal",
        description:
          "Usually the first practical target, because almost nothing else is workable on three broken hours a night. Improvements here often produce the first real relief.",
      },
      {
        title: "Connect with trauma-focused therapy",
        description:
          "Approaches with the strongest evidence include cognitive processing therapy, prolonged exposure, and EMDR. We refer to therapists trained in these and coordinate with them, or work alongside the therapist you already have.",
      },
      {
        title: "Adjust over time, without a deadline",
        description:
          "Recovery from trauma is not linear and anniversaries, reminders, and new stressors can produce setbacks. A setback is part of the course rather than evidence that treatment has failed.",
      },
    ],
  },
  {
    type: "checklist",
    eyebrow: "Between visits",
    heading: "What helps while treatment is underway",
    intro:
      "These support treatment rather than replace it, and they are most useful once sleep has improved even a little.",
    items: [
      {
        title: "Protecting sleep as the first priority",
        description:
          "Sleep loss amplifies intrusion, irritability, and hyperarousal directly. Anything that improves it, including addressing nightmares specifically, tends to improve everything else.",
      },
      {
        title: "Reducing alcohol",
        description:
          "It shortens the time to fall asleep and destroys the quality of the sleep that follows, particularly the stages involved in emotional processing. It reliably worsens PTSD over weeks even when it helps over hours.",
      },
      {
        title: "Grounding techniques for intrusion",
        description:
          "Simple, practised sensory anchors that re-orient you to the present. They work best when rehearsed while calm rather than improvised mid-flashback.",
      },
      {
        title: "Approaching avoidance in small steps",
        description:
          "Not forcing yourself into overwhelming situations, which backfires, but with your therapist choosing the smallest avoided thing and starting there.",
      },
      {
        title: "Telling one person something true",
        description:
          "Isolation is both a symptom and an accelerant. It does not need to be the whole story, and it does not need to be everyone.",
      },
      {
        title: "Planning for anniversaries and known triggers",
        description:
          "Expected difficult dates are far more manageable when they are anticipated. Worth raising at the appointment before, not the one after.",
      },
      {
        title: "Physical activity",
        description:
          "Regular movement helps regulate a nervous system stuck in threat response, and has reasonable supporting evidence in PTSD specifically.",
      },
    ],
  },
  {
    type: "faq",
    eyebrow: "Common questions",
    heading: "About trauma treatment",
    items: [
      {
        question: "Do I have to talk about what happened?",
        answer:
          "Not with your psychiatric provider, and not before you are ready. Building a medication and stabilisation plan requires understanding your current symptoms, not a full account of events. Trauma-focused therapy does eventually involve processing the memory, but that work is paced deliberately and only begins when you are ready for it.",
      },
      {
        question: "Is it still PTSD if the trauma was a long time ago?",
        answer:
          "Yes. PTSD can persist for decades and can also surface years later, often triggered by a life change, a loss, or a reminder. Delayed onset is recognised and treatable, and time passed does not make treatment less effective.",
      },
      {
        question: "What if my experience does not seem bad enough to count?",
        answer:
          "This comes up constantly, particularly with people who compare their experience to someone else's. What determines whether treatment is warranted is the effect on you now, not a ranking of events. Ongoing harm within a relationship or in childhood is frequently underestimated by the person who lived it.",
      },
      {
        question: "Can medication stop flashbacks and nightmares?",
        answer:
          "Some medications reduce trauma-related nightmares meaningfully, and lowering overall arousal typically reduces the frequency and intensity of intrusions. Medication does not remove them entirely on its own, which is why trauma-focused therapy is the core treatment.",
      },
      {
        question: "Can PTSD be treated by video?",
        answer:
          "Yes, and there is direct research support for telehealth delivery of PTSD treatment. Many people find their own home a safer setting than an unfamiliar clinical room. If your presentation needs a level of care beyond outpatient telehealth, your provider will say so plainly.",
      },
      {
        question: "Will treatment make me feel worse before better?",
        answer:
          "Trauma-focused therapy can temporarily raise distress as processing begins, which is why the sequencing matters and why stabilisation usually comes first. Psychiatric treatment aimed at sleep and arousal generally does not carry that pattern.",
      },
      {
        question: "What if I have complex trauma rather than a single event?",
        answer:
          "Prolonged or repeated trauma, especially early in life, produces a broader picture that includes difficulties with emotional regulation, self-concept, and relationships. It is treatable, generally over a longer arc, and the approach is different from single-incident PTSD.",
      },
      {
        question: "Can you work with my trauma therapist?",
        answer:
          "Yes, and we prefer to. With your consent, coordinating medication with the phase of therapy you are in makes both more effective, particularly during active processing work.",
      },
    ],
  },
];
